title: Yet Another Blog
tagline: "@saulpanders"
description: Feel free to bookmark this page to watch for updates
author.name: saulpanders
lang: en-us
plugins:
  - jekyll-remote-theme
remote_theme: zivong/jekyll-theme-hydure
google_analytics: G-3QD5N0KWMZ
